## YAML Template.
---
server:
    port: 7071
    
management:
    endpoints:
        web:
            exposure:
                enabled: "*"
    
spring:
    application:
        name: familybank-xyz-uni-query
#    datasource:
#        url: jdbc:h2:file:./data/fileDb
#        driverClassName: org.h2.Driver
#        username: sa
#        password: 
#        generate-unique-name: false
#    h2:
#        console:
#            enabled: true
##            path: /h2
#        
#    jpa:
#        hibernate:
#            ddl-auto: none
#        show-sql: true
#        database-platform: org.hibernate.dialect.H2Dialect
    logging:
      level:
        ROOT: DEBUG
